In [5]:
print("hello world")


hello world


In [6]:
import numpy as np 
a = np.arange(10).reshape(2,5)
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
b = np.arange(10,20,1).reshape(5,2)
b

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [8]:
a .dot(b)

array([[160, 170],
       [510, 545]])

In [9]:
import numpy as np
m = np.arange(20).reshape(4,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
m.sum(axis=1)
# Sum of each element of row

array([10, 35, 60, 85])

In [11]:

import numpy as np 
a = np.ones(3, dtype=np.int32) # prints 1
print(a)
b = np.linspace(0,np.pi,3) #returns evenly spaced numbers over a specified interval.
b

[1 1 1]


array([0.        , 1.57079633, 3.14159265])

In [12]:
c = a + b
print(c)
print(c.dtype)
d = np.exp(c * 1j)
print(d)
d.dtype

[1.         2.57079633 4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


dtype('complex128')

In [9]:
import numpy as np
a = np.arange(10)**3
print(a)
print(a[2:5]) #print index from 2 to 4
a[0:9:2]  #print up to 8 index including only 2nd element


[  0   1   8  27  64 125 216 343 512 729]
[ 8 27 64]


array([  0,   8,  64, 216, 512])

In [17]:
import numpy as np
def f(x,y):
    return 10 * x + y

b = np.fromfunction(f, (5,4), dtype=int)
print(b)
print(b[3,2])
b[0:5,2]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
32


array([ 2, 12, 22, 32, 42])