In [1]:
print("hello world")


hello world


In [3]:
import numpy as np 
a = np.arange(10).reshape(2,5)
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
b = np.arange(10,20,1).reshape(5,2)
b

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [5]:
a .dot(b)

array([[160, 170],
       [510, 545]])